[View in Colaboratory](https://colab.research.google.com/github/tkms0106/python-data-science/blob/master/python_data_science4_31.ipynb)

In [0]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [0]:
arr1 = np.arange(9).reshape((3,3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
ser1 = Series([0,1,2],index=['T','U','V'])

In [0]:
ser2 = Series([3,4],index=['X','Y'])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2,ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [12]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [13]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [14]:
pd.concat([ser1,ser2],axis=1,keys=['cat1','cat2'])

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [0]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])

In [16]:
dframe1

X         Y         Z
0 -0.787800  0.147164  0.398510
1  0.556179 -1.213702  0.493315
2 -1.525482  1.177207 -0.734118
3  0.870525  0.493057 -0.212249

In [0]:
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])

In [18]:
dframe2

Y         Q         X
0 -0.246737 -0.121785  0.514102
1 -1.938588  2.365929 -0.739421
2  1.298066 -0.719006 -0.257620

In [19]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -0.787800  0.147164  0.398510
1       NaN  0.556179 -1.213702  0.493315
2       NaN -1.525482  1.177207 -0.734118
3       NaN  0.870525  0.493057 -0.212249
0 -0.121785  0.514102 -0.246737       NaN
1  2.365929 -0.739421 -1.938588       NaN
2 -0.719006 -0.257620  1.298066       NaN

In [20]:
pd.concat([dframe1,dframe2], ignore_index=True)

Q         X         Y         Z
0       NaN -0.787800  0.147164  0.398510
1       NaN  0.556179 -1.213702  0.493315
2       NaN -1.525482  1.177207 -0.734118
3       NaN  0.870525  0.493057 -0.212249
4 -0.121785  0.514102 -0.246737       NaN
5  2.365929 -0.739421 -1.938588       NaN
6 -0.719006 -0.257620  1.298066       NaN