[View in Colaboratory](https://colab.research.google.com/github/tkms0106/python-data-science/blob/master/python_data_science3_11.ipynb)

In [0]:
import numpy as np

In [0]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [0]:
A = np.random.randn(10)

In [7]:
A

array([-1.8644461 , -1.87846556, -0.91433383, -0.76740741,  1.66088965,
       -1.87595246, -1.15850829,  0.90219703,  1.30041849, -0.57731618])

In [0]:
B = np.random.randn(10)

In [10]:
B

array([ 0.18680211, -0.81244924,  0.18850021,  0.42765879, -0.04587812,
        0.71757099,  0.4765073 , -0.77659692,  1.66359362,  0.31067223])

In [11]:
np.add(A,B)

array([-1.67764399, -2.69091481, -0.72583362, -0.33974861,  1.61501153,
       -1.15838147, -0.682001  ,  0.12560011,  2.96401211, -0.26664395])

In [13]:
np.maximum(A,B)

array([ 0.18680211, -0.81244924,  0.18850021,  0.42765879,  1.66088965,
        0.71757099,  0.4765073 ,  0.90219703,  1.66359362,  0.31067223])