[View in Colaboratory](https://colab.research.google.com/github/tkms0106/python-data-science/blob/master/python_data_science3_13.ipynb)

In [0]:
import numpy as np

In [0]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [0]:
np.save('my_array', arr)

In [0]:
arr = np.arange(10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [0]:
arr1 = np.load('my_array.npy')

In [0]:
arr2 = np.arange(10)

In [12]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr1

array([0, 1, 2, 3, 4])

In [0]:
np.savez('ziparrays.npz', x=arr1, y=arr2)

In [0]:
archive_array = np.load('ziparrays.npz')

In [21]:
archive_array

In [22]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [0]:
arr = np.array([[1,2,3,4],[4,5,6,7]])

In [24]:
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [0]:
np.savetxt('my_test_text.txt', arr, delimiter=',')

In [27]:
!cat my_test_text.txt

1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00,7.000000000000000000e+00


In [0]:
arr = np.loadtxt('my_test_text.txt', delimiter=',')

In [29]:
arr

array([[1., 2., 3., 4.],
       [4., 5., 6., 7.]])