[View in Colaboratory](https://colab.research.google.com/github/tkms0106/python-data-science/blob/master/python_data_science3_7.ipynb)

In [0]:
import numpy as np

In [0]:
my_list1 = [1,2,3,4]

In [0]:
my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [0]:
my_list2 = [11,22,33,44]

In [0]:
my_lists = [my_list1, my_list2]

In [7]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [0]:
my_array2 = np.array(my_lists)

In [9]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [10]:
my_array2.shape

(2, 4)

In [11]:
my_array2.dtype

dtype('int64')

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [0]:
my_zeros = np.zeros(5)

In [14]:
my_zeros.dtype

dtype('float64')

In [15]:
np.ones(5,5)

TypeError: ignored

In [16]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.empty([3,4])

array([[3.92642585e-316, 2.74655598e-316, 3.95252517e-323,
        2.74655598e-316],
       [3.95252517e-323, 2.74655598e-316, 4.44659081e-323,
        0.00000000e+000],
       [2.74658128e-316, 2.74658128e-316, 2.74658128e-316,
        0.00000000e+000]])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [20]:
np.arange([5,50,2])

TypeError: ignored

In [21]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])