[View in Colaboratory](https://colab.research.google.com/github/tkms0106/python-data-science/blob/master/python_data_science3_8.ipynb)

In [0]:
import numpy as np

In [2]:
5/2

2.5

In [3]:
arr1 = np.array([1,2,3,4],[8,9,10,11])

TypeError: ignored

In [4]:
arr1 = np.array([][1,2,3,4],[8,9,10,11]])

SyntaxError: ignored

In [0]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [6]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [7]:
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [8]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
1 / arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [10]:
arr1 ** 3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])